build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    threshold: 20
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInFiles: 20
    thresholdInObjects: 20
    thresholdInInterfaces: 10

naming:
  FunctionNaming:
    active: true
  TopLevelPropertyNaming:
    active: true

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 4
  WildcardImport:
    active: false
  UnusedParameter:
    active: false

potential-bugs:
  UnsafeCast:
    active: true
